### ISSUE TITLE
support set metadata.recommend when create network-spec

### ISSUE THREAD

**Issue by ianhe8x** [OnFinality-io/onf-cli#4]
onf network-spec create -f 
``` yaml
name: rococo-tick
displayName: Rococo Tick created by cli
protocol: polkadot-parachain
imageRepository: onfinality/rococo-collator
metadata:
  chainspec: tick
  # if start command is not defined as entrypoint, need to explicitly declare here
  command: rococo-collator
  recommend:
    nodeSpec: medium
    storageSize: 20
    imageVersion: rev-468d389
  imageVersion: rev-468d389
```

Allowing `recommend` field be be set in the new created network-spec.
